#include <string.h>

#define UNABTO_PLATFORM_CUSTOM 1
#define NABTO_SET_TIME_FROM_ALIVE 0
#define NABTO_ENABLE_REMOTE_CONNECTION 1


// From tunnel config

#define NABTO_ENABLE_CONNECTION_ESTABLISHMENT_ACL_CHECK 1
#define NABTO_ENABLE_TUNNEL_OPEN_ACL_CHECK 1

#define NABTO_ENABLE_STREAM 1
#define NABTO_STREAM_MAX_STREAMS 1

//#define NABTO_STREAM_RECEIVE_WINDOW_SIZE 2
#define NABTO_STREAM_RECEIVE_WINDOW_SIZE 10 
//#define NABTO_STREAM_SEND_WINDOW_SIZE 8
#define NABTO_STREAM_SEND_WINDOW_SIZE 60


#define NABTO_APPLICATION_EVENT_MODEL_ASYNC 1
#define NABTO_ENABLE_EXTENDED_RENDEZVOUS_MULTIPLE_SOCKETS 0

#define NABTO_CONNECTIONS_SIZE 3
#define NABTO_APPREQ_QUEUE_SIZE NABTO_CONNECTIONS_SIZE

//#define NABTO_ENABLE_DEBUG_PACKETS 1
//#define NABTO_ENABLE_DEBUG_SYSLOG_CONFIG 1
//#define NABTO_ENABLE_GET_LOCAL_IP 1

#define NABTO_ENABLE_DYNAMIC_MEMORY 1

//#define NABTO_ENABLE_TCP_FALLBACK 1

#define NABTO_ENABLE_TUNNEL_TCP 1
#define NABTO_ENABLE_TUNNEL_STATUS_CALLBACKS 1

#define NABTO_ENABLE_LOCAL_PSK_CONNECTION 0

